{% set version = "1.9.1" %}

package:
  name: arlpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/arlpy/arlpy-{{ version }}.tar.gz
  sha256: 98db62383f7e8ad453b3532ebee62d1f050365423fdb85dd3b87a7b6f832d626

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bokeh >=1.4.0
    - numpy >=1.18.1
    - pandas >=1.0.1
    - scipy >=1.4.1
    - utm >=0.5.0

test:
  imports:
    - arlpy
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/org-arl/arlpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ARL Python Tools

extra:
  recipe-maintainers:
    - ocefpaf
