{% set version = "1.9.3" %}

package:
  name: arlpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/arlpy/arlpy-{{ version }}.tar.gz
  sha256: 01673a34267018af3d9ec56b96ef86582254b7593c14f32778d796a8c3d3e739

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - bokeh >=1.4.0
    - numpy >=1.18.1,<2
    - pandas >=1.0.1
    - scipy >=1.4.1
    - utm >=0.5.0

test:
  imports:
    - arlpy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip


about:
  home: https://github.com/org-arl/arlpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ARL Python Tools

extra:
  recipe-maintainers:
    - ocefpaf
