{% set version = "1.7.0" %}

package:
  name: arlpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arlpy/arlpy-{{ version }}.tar.gz
  sha256: 0f8febcba26ef5deef523856b7b8e7a57ae880618c4f08ac4d2ef61354ddd9d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bokeh >=1.2.0
    - numpy >=1.16.2
    - pandas >=0.23.4
    - scipy >=1.2.1
    - utm >=0.4.2

test:
  imports:
    - arlpy

about:
  home: https://github.com/org-arl/arlpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ARL Python Tools

extra:
  recipe-maintainers:
    - ocefpaf
