travis:
  secure:
    BINSTAR_TOKEN: PPEUFBGKUVT3FQYUUDayX9lmM2e70Kv4IvNuqcZMoVYvvyVNUAIrCCGWJXH9UjglOsKPlRzk6WxuHCDYcq2aN0nOE+wmnwBWfy9JHjTuNFVuQnNNCrOdqjxehCMqZWXTg1LN9Q2p1pNW7ZznwGqiG4yx4zPx2nGcLo7uVd+zJUSe1hOXumEL431xA97D5O43m/bvSkwVeKWw42KtVFFXCXgiPggm6AU9gNuWMVJWXG+wi6WiOS5sm8PppicFmFEWYnssnT5plKIWleeWWeREFmMRO/qm5+XWnTv251S3PfpOFbmbUzX8s7I9mqjRNQRtvGYc7bCOTO0NhbKBw+FWL0kkV7K4OBogQH0qFFirIelPcQn6kO7mwHx2WqnGxINac0whfjPi+ZQP56A1vXk8quicFQHAA/qcm3wbPQaxPX4r3aiXus4lp94uHUfDLQJcI5i7NNMy/nfFgmuQDjN/lH1jPPXpVDD23p0hcof5r1csGQp4PH9C7TKVzvBBhHBU1EqxLhsDngEcu6FFFxUu0Ruhn8nqIbHRLs/VwtHjMOva9JTSQ0Y/3JNVd2gyLUlQe66mZtneENha98NBNpOCWciJpjmC1C6Qp/0xj5dmFzPd/jMfUkb2QDjOksvrjkh2ppTBsy5HKIf/rAymACpneyou3LmxtG5U14jA7NIDj0U=
bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
